export const budgetTopicPublicationLimits = {
  maxTopicsPerCategory: 12,
  maxProgramsPerTopic: 12,
  maxTopicNameLength: 14,
} as const;

export const budgetArchivedTopicSlugs: ReadonlySet<string> = new Set([
  "education-and-learning-administration",
  "child-and-family-administration",
  "welfare-health-and-social-security-administration",
  "urban-infrastructure-administration",
  "disaster-and-safety-administration",
  "government-and-finance-administration",
  "culture-sports-and-lifelong-learning-administration",
  "industry-agriculture-and-consumer-administration",
  "environment-and-resource-circulation-administration",
  "community-and-resident-services-administration",
  "welfare-and-public-health-workforce",
  "stable-industry-administration",
] as const);

export const budgetTopicShortNames: Readonly<Record<string, string>> = {
  "school-facility-aging": "学校施設の老朽化",
  "education-and-learning-administration": "教育行政",
  "childcare-services-and-environment": "保育サービス",
  "child-and-family-administration": "子ども・家庭行政",
  "preventive-care-and-community-support": "介護予防",
  "welfare-health-and-social-security-administration": "福祉・保健行政",
  "road-bridge-maintenance": "道路・橋の維持",
  "urban-infrastructure-administration": "都市基盤行政",
  "disaster-readiness": "防災・災害対策",
  "disaster-and-safety-administration": "危機管理",
  "digital-public-services": "デジタル行政",
  "government-and-finance-administration": "行財政運営",
  "access-to-sports": "スポーツ環境",
  "culture-sports-and-lifelong-learning-administration": "文化・スポーツ行政",
  "local-business-support": "中小企業支援",
  "industry-agriculture-and-consumer-administration": "産業・農業行政",
  "decarbonization-and-renewable-energy": "脱炭素",
  "environment-and-resource-circulation-administration": "環境・清掃行政",
  "community-facilities": "地域施設",
  "community-and-resident-services-administration": "地域・区民行政",
  "diverse-learning-and-education-support": "多様な学び",
  "school-health-and-safety": "学校の健康・安全",
  "safe-and-accessible-school-meals": "学校給食",
  "early-childhood-education-support": "幼児教育",
  "learning-experiences-beyond-school": "校外学習",
  "stable-school-and-education-operations": "学校運営",
  "children-youth-places-and-activities": "子どもの居場所",
  "family-benefits-and-medical-support": "子育て給付・医療",
  "child-protection-and-family-care": "子どもの保護",
  "community-child-and-family-support": "子ども・家庭支援",
  "safe-child-support-facilities": "子ども施設の安全",
  "livelihood-security-and-community-welfare": "生活支援・地域福祉",
  "disability-community-life-and-independence": "障害者の地域生活",
  "older-adult-daily-life-and-care": "高齢者の生活支援",
  "maternal-and-child-health": "母子保健",
  "infection-prevention-and-vaccination": "感染症対策",
  "health-screening-and-healthy-lifestyles": "健診・健康づくり",
  "community-health-and-medical-system": "地域医療",
  "food-and-living-hygiene": "食と生活衛生",
  "welfare-and-public-health-workforce": "福祉・保健の人材",
  "national-health-insurance-and-medical-benefits": "国民健康保険",
  "latter-stage-elderly-healthcare": "後期高齢者医療",
  "long-term-care-insurance-and-services": "介護保険",
  "safe-streets-and-cycling": "歩行者・自転車",
  "flood-river-and-drainage-resilience": "豪雨・水害対策",
  "parks-and-public-open-spaces": "公園・広場",
  "urban-green-and-water-conservation": "みどりと水",
  "housing-security-and-quality": "住まいの支援",
  "safe-buildings-and-resilient-neighborhoods": "防災まちづくり",
  "stations-transit-and-community-planning": "駅・交通まちづくり",
  "stable-urban-infrastructure-operations": "都市基盤管理",
  "public-information-and-citizen-voice": "区政情報・区民の声",
  "democratic-governance-elections-and-oversight": "議会・選挙・監査",
  "sustainable-public-finance-and-taxation": "財政・税",
  "evidence-informed-policy-and-partnerships": "データ・官民連携",
  "public-assets-buildings-and-fleet": "公共資産管理",
  "public-workforce-and-administrative-foundation": "行政の人材・業務基盤",
  "libraries-reading-and-knowledge-access": "図書館・読書",
  "cultural-heritage-and-local-history": "文化財・地域史",
  "arts-culture-and-multicultural-exchange": "文化芸術・多文化交流",
  "lifelong-learning-and-community-education": "生涯学習",
  "active-aging-and-community-participation": "生涯現役",
  "interregional-exchange-and-rural-experiences": "地域間交流",
  "urban-agriculture-and-farmland": "都市農業",
  "consumer-rights-and-safe-transactions": "消費者の安全",
  "stable-industry-administration": "産業行政の基盤",
  "waste-collection-and-clean-neighborhoods": "ごみ収集",
  "resource-circulation-and-recycling": "資源循環",
  "clean-safe-and-comfortable-environment": "生活環境",
  "stable-cleaning-and-environment-operations": "清掃事業の基盤",
  "safe-community-and-crime-prevention": "防犯・暮らしの安全",
  "human-rights-gender-equality-and-peace": "人権・平和",
  "community-participation-events-and-support": "地域活動",
  "accessible-local-offices-and-services": "地域窓口・支所",
  "resident-records-family-register-and-identity": "住民記録・戸籍",
  "community-learning-and-civic-facilities": "地域の学び",
};

export const budgetTopicSelectionTerms: Readonly<
  Record<string, readonly string[]>
> = {
  "access-to-sports": ["スポーツ", "運動", "体育", "プール"],
  "accessible-local-offices-and-services": ["総合支所", "出張所", "窓口"],
  "arts-culture-and-multicultural-exchange": [
    "文化",
    "芸術",
    "美術",
    "文学",
    "多文化",
    "外国人",
    "交流",
  ],
  "childcare-services-and-environment": [
    "保育",
    "一時預かり",
    "病児",
    "認定こども園",
  ],
  "child-protection-and-family-care": [
    "児童相談所",
    "一時保護",
    "家庭養育",
    "児童養護",
    "措置費",
    "権利擁護",
  ],
  "children-youth-places-and-activities": [
    "学童",
    "児童館",
    "遊び場",
    "中高生",
    "交流センター",
    "居場所",
  ],
  "community-child-and-family-support": [
    "子育て",
    "家庭",
    "養育",
    "若者",
    "地域活動",
    "相談",
  ],
  "community-health-and-medical-system": ["保健", "医療", "健康危機", "衛生"],
  "community-learning-and-civic-facilities": [
    "生涯学習",
    "学習",
    "講座",
    "教育",
  ],
  "community-participation-events-and-support": [
    "地域活動",
    "町会",
    "自治会",
    "区民",
    "交流",
    "まつり",
  ],
  "disability-community-life-and-independence": [
    "障害",
    "自立",
    "相談",
    "就労",
    "グループホーム",
    "地域生活",
    "補装具",
  ],
  "disaster-readiness": ["防災", "災害", "備蓄", "水防", "避難"],
  "diverse-learning-and-education-support": [
    "特別支援",
    "教育相談",
    "日本語",
    "不登校",
    "ほっとスクール",
    "ICT",
    "学習支援",
    "指導補助",
  ],
  "health-screening-and-healthy-lifestyles": [
    "健診",
    "検診",
    "健康",
    "食育",
    "生活習慣",
  ],
  "evidence-informed-policy-and-partnerships": [
    "データ",
    "統計",
    "官民連携",
    "大学連携",
    "政策研究",
    "行政経営改革",
    "計画行政",
  ],
  "family-benefits-and-medical-support": [
    "手当",
    "医療費",
    "助成",
    "給付",
    "扶養",
    "出産",
  ],
  "food-and-living-hygiene": [
    "食品衛生",
    "生活衛生",
    "環境衛生",
    "検査",
    "狂犬病",
    "動物",
    "害虫",
    "医事薬事",
  ],
  "infection-prevention-and-vaccination": [
    "感染症",
    "予防接種",
    "インフルエンザ",
    "結核",
    "風しん",
    "HPV",
    "帯状疱疹",
  ],
  "latter-stage-elderly-healthcare": ["後期高齢", "広域連合", "保険料", "療養"],
  "libraries-reading-and-knowledge-access": ["図書館", "図書", "読書"],
  "lifelong-learning-and-community-education": [
    "生涯学習",
    "社会教育",
    "区民講座",
    "成人",
    "PTA",
    "学び",
  ],
  "livelihood-security-and-community-welfare": [
    "生活保護",
    "生活困窮",
    "生活支援",
    "地域福祉",
    "民生委員",
    "成年後見",
    "路上生活",
  ],
  "local-business-support": [
    "中小企業",
    "事業者",
    "商店",
    "産業",
    "創業",
    "経営",
    "雇用",
    "ものづくり",
  ],
  "long-term-care-insurance-and-services": [
    "介護サービス",
    "介護給付",
    "介護保険",
    "福祉用具",
    "住宅改修",
  ],
  "maternal-and-child-health": [
    "妊婦",
    "妊産婦",
    "乳幼児",
    "母子",
    "新生児",
    "産後",
    "両親",
  ],
  "national-health-insurance-and-medical-benefits": [
    "国民健康保険",
    "療養",
    "医療",
    "保険給付",
    "納付金",
    "出産育児",
    "葬祭",
  ],
  "older-adult-daily-life-and-care": [
    "高齢者",
    "見守り",
    "在宅",
    "シニア",
    "終活",
  ],
  "parks-and-public-open-spaces": ["公園", "緑地", "広場"],
  "preventive-care-and-community-support": [
    "介護予防",
    "地域包括",
    "認知症",
    "家族介護",
    "生活支援",
  ],
  "public-workforce-and-administrative-foundation": [
    "職員採用",
    "職員研修",
    "健康保持",
    "文書管理",
    "法務",
    "安全衛生",
    "業務改善",
    "公務災害",
  ],
  "resident-records-family-register-and-identity": [
    "住民記録",
    "戸籍",
    "住民票",
    "社会保障・税番号",
  ],
  "safe-and-accessible-school-meals": ["給食", "食育"],
  "safe-child-support-facilities": [
    "児童施設",
    "児童館",
    "子育て支援施設",
    "青少年交流センター",
  ],
  "safe-community-and-crime-prevention": [
    "防犯",
    "犯罪被害",
    "安全安心",
    "助け合い",
  ],
  "safe-buildings-and-resilient-neighborhoods": [
    "耐震",
    "不燃",
    "防災街づくり",
    "建築",
    "空家",
  ],
  "safe-streets-and-cycling": [
    "歩道",
    "自転車",
    "交通安全",
    "道路照明",
    "通学路",
    "放置自転車",
  ],
  "school-facility-aging": ["改築", "改修", "整備", "建設", "老朽"],
  "school-health-and-safety": [
    "健康診断",
    "保健衛生",
    "検査検診",
    "健康",
    "安全",
  ],
  "stable-cleaning-and-environment-operations": [
    "清掃",
    "ごみ",
    "資源",
    "収集",
    "環境",
  ],
  "stable-school-and-education-operations": [
    "学校運営",
    "学校管理",
    "教育運営",
    "校務",
    "教職員",
    "学校職員",
    "就学",
  ],
  "stable-urban-infrastructure-operations": [
    "道路管理",
    "公園管理",
    "土木",
    "測量",
    "台帳",
    "インフラ",
  ],
  "stations-transit-and-community-planning": [
    "駅",
    "鉄道",
    "交通",
    "バス",
    "沿線",
    "まちづくり",
  ],
  "sustainable-public-finance-and-taxation": [
    "財政",
    "税",
    "公金",
    "会計",
    "特別区債",
    "収納",
    "徴収",
  ],
};

export function getBudgetTopicShortName(topicSlug: string): string {
  const name = budgetTopicShortNames[topicSlug];
  if (!name) {
    throw new Error(`短いtopic名が未定義です: ${topicSlug}`);
  }
  return name;
}

export function getBudgetTopicPublicationStatus(
  topicSlug: string
): "published" | "archived" {
  return budgetArchivedTopicSlugs.has(topicSlug) ? "archived" : "published";
}
